name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      env:
        FORMSPREE_URL: ${{ secrets.FORMSPREE_URL }}
      run: |
        echo "Deploying to $FORMSPREE_URL"
        # Add your deployment script here